source 'https://code.stripe.com'
source 'https://rubygems.org'
ruby '2.1.4'
gem 'rails', '4.1.5'
gem 'passenger'
gem 'sqlite3', :group => :development
gem 'pg', :group => :production
gem 'rails_12factor', group: :production
gem 'paperclip'
gem 'aws-sdk'
gem 'acts_as_api'
gem 'devise'
gem 'jquery-rails'
gem 'jquery-ui-rails', '~> 4.2.1'
gem "nested_form"
gem 'shadowbox-rails'
gem 'sass-rails'
gem 'protected_attributes'
gem 'multi_fetch_fragments'
gem 'resque'
gem 'resque-scheduler'
gem 'delayed_paperclip'
gem 'sunspot_rails'
gem 'sunspot_solr'
gem 'roo'
gem 'twilio-ruby'
gem 'deep_cloneable', '~> 1.6.0'
gem 'nprogress-rails'
gem 'stripe'
gem 'acts_as_list'
gem 'actionview-encoded_mail_to'
gem 'uglifier', '>= 1.3.0'
gem 'httparty'
gem 'geocoder'
gem 'jquery-easing-rails'
gem "parsley-rails"
gem 'newrelic_rpm'
gem "select2-rails"
gem 'houston'
gem 'gcm'
gem "recaptcha", :require => "recaptcha/rails"
gem 'truncate_html'
gem "remotipart"
gem 'font-awesome-rails'
gem 'sweet-alert'
gem 'mandrill_mailer'
gem 'gibbon'
gem 'forecast_io'

#gem 'resque-pool'
#gem 'capybara'
#gem 'non-stupid-digest-assets'