monthly_billing:
  cron: "0 0 1 * *"
  class: MonthlyBilling
  args:
  description: Handles monthly billing on midnight of the first day of every month

daily_billing:
  cron: "0 0 * * *"
  class: DailyBilling
  args:
  description: Track billing days per project_user every night at midnight