monthly_billing:
  cron: "0 0 1 * *"
  class: MonthlyBilling
  args:
  description: Handle monthly billing

billing_day:
  cron: "0 * * * *"
  class: BillingDay
  args:
  description: Track billing days per project_user