monthly_billing:
  cron: "0 0 1 * *"
  class: MonthlyBilling
  args:
  description: Handle monthly billing

daily_billing:
  cron: "0 * * * *"
  class: DailyBilling
  args:
  description: Track billing days per project_user