development:
  bucket: buildhawk-dev
  s3_host_alias: d2bs59u537xlvu.cloudfront.net
  access_key_id: AKIAJC7K2IXFBN7BU2NA
  secret_access_key: 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

test:
  bucket: buildhawk-dev
  s3_host_alias: d2bs59u537xlvu.cloudfront.net
  access_key_id: AKIAJC7K2IXFBN7BU2NA
  secret_access_key: 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

production:
  bucket: buildhawk
  s3_host_alias: dw9f6h00eoolt.cloudfront.net
  access_key_id: AKIAJC7K2IXFBN7BU2NA
  secret_access_key: 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