development:
  bucket: buildhawk-dev
  access_key_id: AKIAIG3O6L7Y7SE2JJGA
  secret_access_key: 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

test:
  bucket: buildhawk-dev
  access_key_id: AKIAIG3O6L7Y7SE2JJGA
  secret_access_key: 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

production:
  bucket: buildhawk
  access_key_id: AKIAIG3O6L7Y7SE2JJGA
  secret_access_key: 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